### ISSUE TITLE
bug: SDK - Sundry issues

### ISSUE THREAD

**Issue by kpalania** [snowpal/pitch-building-blocks-sdk#62]
# Building Blocks SDK

- [ ] 1. Move Project Block is missing.

<img width="200" alt="Screenshot 2023-05-31 at 3 06 25 PM" src="https://github.com/snowpal/pitch-building-blocks-sdk/assets/841459/b053aa46-cd47-491b-b97e-5110d1f932b8">

# Project Management SDK

- [ ] 1. Move Project is missing

<img width="316" alt="Screenshot 2023-06-01 at 5 42 26 AM" src="https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/500f57a8-d47f-4761-8259-6fc50ffce880">

# Content Management SDK

# Classroom SDK

# Conversation SDK

# Status SDK

**Comment by kpalania** [comment]
@AnishKhatri 



![Image](https://github.com/snowpal/pitch-building-blocks-sdk/assets/841459/5f024c31-28db-478a-8428-a61b176808c5)

**Comment by AnishKhatri** [comment]
_Superseded by_

- [ ] 1. `Add Key` - add in all 5 directories calling out the documentation issue to add allowed key type values
- [ ] 2. `Copy project block` - remove from _building blocks_
- [ ] 3. `Copy project pod` - add missing attributes _all tasks_ and _all checklists_
- [ ] 4. Remove redundant endpoints from _Project Keys.1_ in _project management_ 
  - [ ] 4a. move the `projectListId` param to the respective endpoint and callout for that
- [ ] 5. Remove `Copy project project` endpoint from _project management_

**Comment by kpalania** [comment]
https://github.com/snowpal/pitch-api-gateway/pull/788

**Comment by kpalania** [comment]
@AnishKhatri This is complete.

**Comment by kpalania** [comment]
https://github.com/snowpal/pitch-api-gateway/releases/tag/v2.0.2P
