### ISSUE TITLE
fix: sundry SDK issues

### ISSUE THREAD

**Issue by kpalania** [snowpal/pitch-building-blocks-sdk#65]
- [x] 1. fix directory and file names in:
  - [x] i. Status SDK
  - [x] ii. Conversation SDK
  - [x] iii. Content Management SDK
  - [x] iv. Project Management SDK
  - [x] v. Classroom SDK
- [x] 2. Fix `GO Status` SDK Endpoints 
  - [x] a. 5.2
  - [x] b. 5.3
  - [x] c. 5.4
- [x] 3. Add missing `GO Status` SDK endpoints
  - [x] a. 4.2
  - [x] b. 4.5
  - [x] c. 4.7
  - [x] d. 8.2
  - [x] e. 8.5
  - [x] f. 8.7

**Comment by AnishKhatri** [comment]
### PR: https://github.com/snowpal/pitch-go-status-sdk/pull/52
