### ISSUE TITLE
test: existing recipes in SDKs

### ISSUE THREAD

**Issue by kpalania** [snowpal/pitch-building-blocks-sdk#66]
- [x] 1. `Content Management SDK`: Test existing recipes
- [x] 2. `Project Management SDK`: Test existing recipes (_open_)
- [x] 3. `Conversation SDK`: Test existing recipes (_wip_)
- [x] 4. `Classroom SDK`: Test existing recipes

**Comment by AnishKhatri** [comment]
@kpalania for `Project Management SDK`

- I am getting an error, while creating _project_ in a _key_. Hence 4, 6, 7, 8 & 9 recipes fails.
- I have copied config code and created [PR](https://github.com/snowpal/pitch-project-management-sdk/pull/6)
