### ISSUE TITLE
enh: add a recipe to initialize user (meant primarily for testing & demo purposes)

### ISSUE THREAD

**Issue by kpalania** [snowpal/pitch-building-blocks-sdk#71]
### Time Spent 

| Date | Time |
| ---: | ---: | 
| [06/14/23](https://github.com/snowpal/pitch-ui-docs/blob/develop/status/2023/6_june/2023_06_14_wed.json) | 4.0 |
| [06/15/23](https://github.com/snowpal/pitch-ui-docs/blob/develop/status/2023/6_june/2023_06_15_thu.json) | 8.0 |
| [06/19/23](https://github.com/snowpal/pitch-ui-docs/blob/develop/status/2023/6_june/2023_06_19_mon.json) | 3.0 |
| [06/21/23](https://github.com/snowpal/pitch-ui-docs/blob/develop/status/2023/6_june/2023_06_21_wed.json) | 1.0 |
| **Total** | **16.0** |

This is what the recipe should do.

## Acceptance Criteria

- [x] 1. ~~It will accept the following arguments: `API Key`, `Product Code`, `Server URL`.~~
- [x] 2. It will do the following:
  - [x] 2a. Sign up a new user using an email address it computes (`not passed by recipe executor, or tester`). Let's use an email in this format: `apiuser_rec[1-1000]_[bb|cm|pm|gs|cr]@yopmail.com`. _Example_: `apiuser_rec99_bb@yopmail.com`.
  - [x] 2b. If email already exists, and an error is thrown by API, it should silently try a different email again, **till** it succeeds. (_Use a method to randomize the incremented number in the email, and use it repeatedly_).
  - [x] 2c. Once registered, it will activate the user.
  - [x] 2d. It will then sign in the user.
  - [x] 2e. Store the JWT code in a variable as we'll need this later (_to display to the tester_).
  - [x] 2f. Create a Key (_again, use dynamic names_) of every legal type. Meaning, if recipe is in `Building Blocks` API, create a Key of all types but if it is in `Classroom` API, just create a `Teacher Key`. (_Ignore recipe for Conversation API, for now_).
  - [x] 2g. Create a Block in every Key that was created above.
  - [x] 2h. Create a Pod in every Key that was created above.
  - [x] 2i. Create a Block Pod in every Block that was created above.
  - [x] 2j. Sign up as second user.
  - [x] 2k. Sign in as first user, and share every Block, Pod and Block Pod with second user.
- [x] 3. Print the following in the format below.
  - [x] 3a. Print Users registered: 
    ```
       ## Registered Users
       - apiuser_rec99_bb@yopmail.com | <JWT Code>
       - apiuser_rec102_bb@yopmail.com | <JWT Code>
     ```
- [x] 3b. Print Resources Created: 
    ```
       ## Resources Created for user: <User Email>
       - Get Keys Response
       - Iterate through Keys, print Get Blocks
       - Iterate through Keys, print Get Pods
       - Iterate through Blocks, print Get Block Pods
    ```
- [x] 3c. Print Notifications Received: 
    ```
       ## Notifications received by the user: <User Email>
       - Get Notifications Response
       - Iterate through Notifications, print Notification
    ```

> Plan to commit frequently so I can check out how it is evolving but at the very least, commit a _partial_ version at the end of the session.

**Comment by kpalania** [comment]
@AnishKhatri Add `Acceptance Criteria` videos, for _every SDK_.

**Comment by AnishKhatri** [comment]
## Recording

https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/a6bc41f7-4279-4db3-9c85-d923f081a583

**Comment by AnishKhatri** [comment]
### PR: https://github.com/snowpal/pitch-building-blocks-sdk/pull/77
