### ISSUE TITLE
pr: fix pr comments for all sdk

### ISSUE THREAD

**Issue by AnishKhatri** [snowpal/pitch-building-blocks-sdk#79]
### Time Spent 

| Date | Time |
| ---: | ---: | 
| [06/22/2023](https://github.com/snowpal/pitch-ui-docs/blob/develop/status/2023/6_june/2023_06_22_thu.json) | 3.0 |
| [06/23/2023](https://github.com/snowpal/pitch-ui-docs/blob/develop/status/2023/6_june/2023_06_23_fri.json) | 5.0 | 
| **Total** | **8.0** | 

### PR Feedback - `06/21/2023`

- [x] 1. Replace `log.Info` where there are arguments
- [x] 2. Get rid of wrappers such as `AddKey` & all the other add key methods in `recipe.helper.go`
- [x] 3. Move all the share related methods in `recipe.helper.go` to a new collaboration file
- [x] 4. Add a `first` method to helper, so we don't need to a `[0]` all over the place
- [x] 5. Remove `shareBlock` in one of the newer recipes
- [x] 6. Fix _err_ variable issues, e.g. `displayContent`

> Make all these changes for all the SDKs

**Comment by kpalania** [comment]
My LOE is `2.0`.

@AnishKhatri

**Comment by AnishKhatri** [comment]
## AC Recordings

### Content Management SDK
https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/0f59b9c3-8622-4360-933e-05188e3d8884

### Project Management SDK
https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/a17bddf7-f583-46f7-96e0-ef500d3eba49

### Classroom SDK
https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/d5826982-7b56-4404-bb4e-1ea0270886de

### Conversation SDK
https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/64210fc6-7822-473d-8e07-74514ab3c88a

### Building Blocks SDK
https://github.com/snowpal/pitch-building-blocks-sdk/assets/3121529/ca341c87-3836-4e60-8028-f68f328fc4e1

@kpalania
